### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by Icesofty** [Icesofty/Digital-Currency#4]
- [ ] Explain how to Deploy the App on a Live VPS

- [ ] Explain how to install MongoDB

**Comment by centralhardware** [comment]
the best way would be to wrap the application in docker with docker compose, this will solve both of these problems

**Comment by JONAS402** [comment]
is it possible for you to provide some more detailed information on the admin user process? 

currently i am getting: 
`TypeError: Cannot read property 'username' of undefined
    at /home/sysadmin/Digital-Currency/app.js:300:50`

i am sure this is because i have not added the user correctly, i have tried creating a users collection on the tonkenDB database, is this correct?

**Comment by florianjs** [comment]
> is it possible for you to provide some more detailed information on the admin user process?
> 
> currently i am getting:
> `TypeError: Cannot read property 'username' of undefined at /home/sysadmin/Digital-Currency/app.js:300:50`
> 
> i am sure this is because i have not added the user correctly, i have tried creating a users collection on the tonkenDB database, is this correct?

This is an old project. When requested, 'username' is 'undefined'.  So you probably have an issue with your Database or an issue connecting your DB to the project
